### ISSUE TITLE
Issue with CelikAPI 1.4.1 version

### ISSUE THREAD

**Issue by veselinovicnikola** [neman/BashChelik#5]
I have problem when use new CelikAPI.dll version 1.4.1. Error that happens is that version is not supported. Can you help me with this?

**Comment by neman** [comment]
I have checked, the new version of Celik Api was released at 07.06.2024.

I will update the existing code, to align with the new version.

**Comment by neman** [comment]
You can try now with 1.4.1. The code was just updated to support it.
